name: Move Files

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  move_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move files and folders
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/
            mkdir docs  # Create the destination directory

            if [ -d "public" ]; then
              mv public/* docs/  # Move all files and folders
            else
              echo "public directory does not exist."
          else
              echo "docs directory does not exist."
          fi

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Move files and folders"
          git push