name: Rename Folder

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  rename_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rename Folder
        run: |
          if [ -d "public" ]; then  
            mv public docs
          else
            echo "public directory does not exist."
          fi

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Move files and folders"
          git push